---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  # This is the resource Identifier
  LaravelFunction:
    # This resource creates a Lambda function.
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'laravel'
      Description: 'laravel function description'
      CodeUri: ./storage/latest.zip
      Handler: laravel/public/index.php
      Timeout: 30 # in seconds (API Gateway has a timeout of 30 seconds)
      Runtime: provided
      MemorySize: 3008
      Role: !GetAtt LaravelFunctionExecutionRole.Arn
      Layers:
        - 'arn:aws:lambda:us-east-1:209497400698:layer:php-73-fpm:2'
      Environment:
        Variables:
          SQS_JOB_QUEUE_ARN: !GetAtt JobQueue.Arn
          SQS_PREFIX: !Sub 'https://sqs.${AWS::Region}.amazonaws.com/${AWS::AccountId}'
          SQS_QUEUE: !GetAtt JobQueue.QueueName
      Events:
        # The function will match all HTTP URLs
        LaravelRootApi:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        LaravelSubPathApi:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        LaravelJobQueue:
          Type: SQS
          Properties:
            Queue: !GetAtt JobQueue.Arn
            BatchSize: 1
  LaravelFunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Laravel_Job_Role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: allowLambdaLogging
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
        - PolicyName: allowSqsTriggerAndPost
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage*
                  - sqs:DeleteMessage
                  - sqs:ReceiveMessage
                  - sqs:GetQueueAttributes
                  - sqs:ChangeMessageVisibility
                Resource: !GetAtt JobQueue.Arn
  JobQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: Laravel_Job_Queue
      DelaySeconds: 30

Outputs:
  LaravelFunctionApi:
    Description: 'URL of our function in the Gateway API *Prod* environment'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
  JobQueueName:
    Description: 'Name of our Job Queue'
    Value: !GetAtt JobQueue.QueueName
  JobQueueArn:
    Description: 'ARN of our Job Queue'
    Value: !GetAtt JobQueue.Arn
