---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  # This is the resource Identifier
  LaravelFunction:
    # This resource creates a Lambda function.
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'laravel'
      CodeUri: ./storage/latest.zip
      Handler: laravel/public/index.php
      Timeout: 30 # in seconds (API Gateway has a timeout of 30 seconds)
      Runtime: provided
      MemorySize: 3008
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt JobQueue.QueueName
      Layers:
        - 'arn:aws:lambda:us-east-1:209497400698:layer:php-73-fpm:2'
      Environment:
        Variables:
          # Laravel environment variables
          # @todo: Should probably make these configurable in config/bref.php file
          APP_STORAGE: '/tmp'     # The only thing we can write to in Lambda
          BREF_LAMBDA_ENV: true   # Make it easy to determine we are running in Lambda. Use `runningInLambda()` helper.
          LOG_CHANNEL: stderr     # Log to stderr so that everything goes to cloudwatch.
          CACHE_DRIVER: file
          SESSION_DRIVER: array
      Events:
        # The function will match all HTTP URLs
        LaravelRootApi:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        LaravelSubPathApi:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        LaravelJobQueue:
          Type: SQS
          Properties:
            Queue: !GetAtt JobQueue.Arn
            BatchSize: 1
  JobQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: Laravel_Job_Queue

Outputs:
  LaravelFunctionApi:
    Description: 'URL of our function in the *Prod* environment'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
  JobQueueName:
    Description: 'Name of our Job Queue'
    Value: !GetAtt JobQueue.QueueName
  JobQueueArn:
    Description: 'ARN of our Job Queue'
    Value: !GetAtt JobQueue.Arn
