---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Environment:
      Variables:
        # Laravel environment variables
        # @todo: Should probably make these configurable in config/bref.php file
        APP_STORAGE: '/tmp'     # The only thing we can write to in Lambda
        BREF_LAMBDA_ENV: true   # Make it easy to determine we are running in Lambda. Use `runningInLambda()` helper.
        LOG_CHANNEL: stderr     # Log to stderr so that everything goes to cloudwatch.
        CACHE_DRIVER: file
        SESSION_DRIVER: array

Resources:
  Website:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'laravel-website'
      CodeUri: ./storage/latest.zip
      Handler: laravel/public/index.php
      Timeout: 30 # in seconds (API Gateway has a timeout of 30 seconds)
      Runtime: provided
      Layers:
        - 'arn:aws:lambda:us-east-1:209497400698:layer:php-73-fpm:1'
      Events:
        # The function will match all HTTP URLs
        HttpRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        HttpSubPaths:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
  Artisan:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'laravel-artisan'
      CodeUri: ./storage/latest.zip
      Handler: laravel/artisan
      Timeout: 120
      Runtime: provided
      Layers:
        - 'arn:aws:lambda:us-east-1:209497400698:layer:php-72:1'


Outputs:
  DemoHttpApi:
    Description: 'URL of our function in the *Prod* environment'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
